[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "CHANGE_ME"

[auth.google]
client_id = ""
client_secret = "CHANGE_ME"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"

[connections.postgresql]
url = 'postgresql://postgres:postgres@127.0.0.1:54322/postgres'